<?php
error_reporting(E_ALL);

$config = array();

$config['phone'] = '(888) 888-8888';
$config['company_email'] = 'care@smartpetglamgoods.com';
$config['site_url'] = 'smartpetglamgoods.com';
$config['company_name'] = 'Company Name';
$config['company_address'] = 'Address1, Address2'; 
$config['company_state'] = 'State';

$config['return_address'] = "Return Address";

$config['product_name'] = 'Smart Pet Glam Goods';
$config['card_statement'] = 'Smart Pet Glam Goods';
$config['cs_hours'] = 'Monday-Saturday: 9 am to 5 pm EST';

$config['max_qty'] = 10;
$config['cart_page'] = "cart.php";
$currency ='$';

$config['productSpecs'] = array(

//Product 1
	
	1 => array(
		'id' => 210, 
		'nm' => "Dog Cage Flooring Mat", 
		'prc' => 1.67,
		'shpprc' => 0.00,
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-1.png",
		'img4' => "images/products/prod1-desc-img.png",
		'desc' => "Ensure your furry friend's comfort and hygiene with our durable dog cage flooring mat, designed to provide a soft and supportive surface for lounging and play. Crafted from high-quality materials, it's easy to clean and resistant to odors, offering a sanitary solution for your pet's living space. ",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Cosmetic',
		'color' => 'Pink'
		),
			
//Product 2	
		
	2 => array(
		'id' => 211,  
		'nm' => "Slow Feeder Pet Bowls", 
		'prc' => 1.89,
		'shpprc' => 0.00,
		'product-type' => '', 
		'altnm' => "", 
		'img' => "images/products/prod-2.png",
		'img4' => "images/products/prod2-desc-img.png",
		'desc' => "Promote healthy eating habits for your pet with our slow feeder pet bowls, designed to encourage slower consumption and reduce the risk of digestive issues. Featuring intricate patterns and obstacles, they challenge your pet to eat at a more measured pace, fostering better digestion and overall well-being.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'size' => "",
		'category' => 'Cosmetic',
		'color' => 'Black'
	),
	
//Product 3
	
	3 => array(
		'id' => 212,  
		'nm' => "Rolling Cat Toy", 
		'prc' => 1.99,
		'shpprc' => 0.00,
		'product-type' => 'cloth', 
		'altnm' => "", 
		'img' => "images/products/prod-3.png",
		'img4' => "images/products/prod3-desc-img.png",
		'desc' => "Keep your feline friend entertained for hours with our rolling cat toy, designed to engage their natural instincts and provide endless fun. With its enticing design and unpredictable movements, it stimulates play and exercise, promoting a healthy and happy cat.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Cosmetic',
		'color' => 'Beige'
	),

//Product 4
		
	4 => array(
		'id' => 213,  
		'nm' => "Pet Hair Remover", 
		'prc' => 12.49,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-4.png",
		'img4' => "images/products/prod4-desc-img.png",
		'desc' => "Effortlessly eliminate pet hair from your home with our innovative pet hair remover, designed for efficient cleaning on any surface. Featuring a durable and ergonomic design, its specially engineered bristles capture and lift stubborn fur with ease, leaving your furniture, carpets, and clothes looking pristine.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Cosmetic',
		'color' => 'Pink'
		
	),

//Product 5
		
	5 => array(
		'id' => 214,  
		'nm' => "Leather Dog Collar", 
		'prc' => 49.99,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-5.png",
		'img4' => "images/products/prod5-desc-img.png",
		'desc' => "This stylish leather dog collar combines durability with comfort, ensuring your pet looks great while staying secure. Made from high-quality, genuine leather, it features a sturdy buckle and reinforced stitching for added strength. The collar's adjustable design provides a perfect fit for dogs of all sizes. Available in multiple colors, it offers both functionality and fashion for your furry friend.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Cosmetic',
		'color' => 'Multi Color'
	),

//Product 6
		
	6 => array(
		'id' => 215,  
		'nm' => "Poop Bag Holder", 
		'prc' =>  59.99,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-6.png",
		'img4' => "images/products/prod6-desc-img.png",
		'desc' => "This compact and durable Poop Bag Holder is designed for pet owners on the go. Easily attachable to any leash, it ensures you're always prepared for clean-up duties. Made from high-quality materials, it features a convenient dispenser opening for quick and easy access. With its sleek design and secure fit, it’s an essential accessory for any dog walker.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Cosmetic',
		'color' => 'Black'
	),

//Product 7
		
	7 => array(
		'id' => 216,  
		'nm' => "Grooming Steam Comb", 
		'prc' => 69.99,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-7.png",
		'img4' => "images/products/prod7-desc-img.png",
		'desc' => "The Grooming Steam Comb combines innovative steam technology with precision grooming for sleek, frizz-free hair. Ideal for all hair types, it gently detangles and smooths, leaving hair shiny and manageable. Lightweight and easy to use, it delivers salon-quality results at home.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Gadgets',
		'color' => 'wooden'
	),

//Product 8
		
	8 => array(
		'id' => 217,  
		'nm' => "Pet Grooming Gloves", 
		'prc' => 119.99,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-8.png",
		'img4' => "images/products/prod8-desc-img.png",
		'desc' => "Pet Grooming Gloves make grooming your furry friend a breeze, combining comfort and efficiency in one tool. The flexible, slip-on design mimics the touch of your hand for a soothing massage while removing loose fur, dirt, and dander. The soft rubber tips ensure a gentle yet effective grooming experience. These gloves are perfect for pets with short or long hair, enhancing their coat's health and shine.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Gadgets',
		'color' => 'Black'
	),

//Product 9
		
	9 => array(
		'id' => 218,  
		'nm' => "Portable Wooden Hammock", 
		'prc' => 159.99,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-9.png",
		'img4' => "images/products/prod9-desc-img.png",
		'desc' => "The Portable Wooden Hammock offers relaxation on the go with its sturdy yet lightweight wooden frame and comfortable fabric sling. Easy to assemble and disassemble, it's perfect for outdoor adventures or lounging at home. Enjoy the blend of durability and elegance, making it an ideal companion for any leisure activity.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Cosmetic',
		'color' => 'White'
	),


//Product 10
		
	10 => array(
		'id' => 219,  
		'nm' => "Wooden Pet House ", 
		'prc' => 189.99,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-10.png",
		'img4' => "images/products/prod10-desc-img.png",
		'desc' => "The Pet Wooden House provides a cozy and secure retreat for your furry friend, blending seamlessly with your home decor. Crafted from durable wood, it offers a sturdy and long-lasting shelter for pets of all sizes. The elevated design helps keep your pet off the ground, while the weather-resistant construction ensures comfort in various conditions. With its charming aesthetic and functional design, this wooden house is a delightful addition to any pet-friendly household.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Gadgets',
		'color' => 'Shiny Gold'
	),

//Product 11
		
	11 => array(
		'id' => 220,  
		'nm' => "Terrarium Home Decor", 
		'prc' => 199.99,
		'shpprc' => 0.00, 
		'product-type' => 'cloth',
		'altnm' => "", 
		'img' => "images/products/prod-11.png",
		'img4' => "images/products/prod11-desc-img.png",
		'desc' => "Terrarium Home Decor adds a touch of greenery and elegance to any living space. These miniature gardens encased in glass create a serene and captivating environment. Perfect for plant enthusiasts or those looking to bring the outdoors inside, they require minimal maintenance and can thrive in various light conditions.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Gadgets',
		'color' => 'Silver'
	),

//Product 12
		
	12 => array(
		'id' => 221,  
		'nm' => "Wooden Scratch Pad", 
		'prc' => 239.99,
		'shpprc' => 0.00, 
		'product-type' => '',
		'altnm' => "", 
		'img' => "images/products/prod-12.png",
		'img4' => "images/products/prod12-desc-img.png",
		'desc' => "The Wooden Scratch Pad provides a natural and durable surface for your cat's scratching needs. Made from high-quality wood, it's designed to withstand even the most vigorous scratching. The pad helps to keep your cat's claws healthy and also protects your furniture from damage. Its compact size and sleek design make it a stylish addition to your home.",
		'points' => "",
		'term' => "By placing an order with us you will be charged {$currency} __prc__ + $0.00 for S&amp;H for One Time for  __prdname__. If you are not completely satisfied with your purchase   __prdname__ at any time, please call {$config['phone']} or email {$config['company_email']}, {$config['cs_hours']}. You will receive your package within 2-5 business days of payment via USPS First Class Mail. I agree that my credit card charge will appear as {$config['card_statement']}.",
		'details' =>"",
		'category' => 'Gadgets',
		'color' => 'White'
	),

);

$config['shippingRates'] = array(
	'US' => array('s'=> 70, 
		'h'=> 0.00,
		'r' => 0
	)
);

$config['countries'] = array(
	'US'	=>	'United States',
	'AF'	=>	'Afghanistan',
	'AL'	=>	'Albania',
	'DZ'	=>	'Algeria',
	'AS'	=>	'American Samoa',
	'AD'	=>	'Andorra',
	'AO'	=>	'Angola',
	'AI'	=>	'Anguilla',
	'AQ'	=>	'Antarctica',
	'AG'	=>	'Antigua And Barbuda',
	'AR'	=>	'Argentina',
	'AM'	=>	'Armenia',
	'AW'	=>	'Aruba',
	'AU'	=>	'Australia',
	'AT'	=>	'Austria',
	'AZ'	=>	'Azerbaijan',
	'BS'	=>	'Bahamas',
	'BH'	=>	'Bahrain',
	'BD'	=>	'Bangladesh',
	'BB'	=>	'Barbados',
	'BY'	=>	'Belarus',
	'BE'	=>	'Belgium',
	'BZ'	=>	'Belize',
	'BJ'	=>	'Benin',
	'BM'	=>	'Bermuda',
	'BT'	=>	'Bhutan',
	'BO'	=>	'Bolivia',
	'BA'	=>	'Bosnia And Herzegowina',
	'BW'	=>	'Botswana',
	'BV'	=>	'Bouvet Island',
	'BR'	=>	'Brazil',
	'IO'	=>	'British Indian Ocean Territory',
	'BN'	=>	'Brunei Darussalam',
	'BG'	=>	'Bulgaria',
	'BF'	=>	'Burkina Faso',
	'BI'	=>	'Burundi',
	'KH'	=>	'Cambodia',
	'CM'	=>	'Cameroon',
	'CV'	=>	'Cape Verde',
	'KY'	=>	'Cayman Islands',
	'CF'	=>	'Central African Republic',
	'TD'	=>	'Chad',
	'CL'	=>	'Chile',
	'CN'	=>	'China',
	'CX'	=>	'Christmas Island',
	'CC'	=>	'Cocos (Keeling) Islands',
	'CO'	=>	'Colombia',
	'KM'	=>	'Comoros',
	'CG'	=>	'Congo',
	'CD'	=>	'Congo, The Democratic Republic Of The',
	'CK'	=>	'Cook Islands',
	'CR'	=>	'Costa Rica',
	'CI'	=>	'Cote D\'Ivoire',
	'HR'	=>	'Croatia (Local Name: Hrvatska)',
	'CU'	=>	'Cuba',
	'CY'	=>	'Cyprus',
	'CZ'	=>	'Czech Republic',
	'DK'	=>	'Denmark',
	'DJ'	=>	'Djibouti',
	'DM'	=>	'Dominica',
	'DO'	=>	'Dominican Republic',
	'TP'	=>	'East Timor',
	'EC'	=>	'Ecuador',
	'EG'	=>	'Egypt',
	'SV'	=>	'El Salvador',
	'GQ'	=>	'Equatorial Guinea',
	'ER'	=>	'Eritrea',
	'EE'	=>	'Estonia',
	'ET'	=>	'Ethiopia',
	'FK'	=>	'Falkland Islands (Malvinas)',
	'FO'	=>	'Faroe Islands',
	'FJ'	=>	'Fiji',
	'FI'	=>	'Finland',
	'FR'	=>	'France',
	'FX'	=>	'France, Metropolitan',
	'GF'	=>	'French Guiana',
	'PF'	=>	'French Polynesia',
	'TF'	=>	'French Southern Territories',
	'GA'	=>	'Gabon',
	'GM'	=>	'Gambia',
	'GE'	=>	'Georgia',
	'DE'	=>	'Germany',
	'GH'	=>	'Ghana',
	'GI'	=>	'Gibraltar',
	'GR'	=>	'Greece',
	'GL'	=>	'Greenland',
	'GD'	=>	'Grenada',
	'GP'	=>	'Guadeloupe',
	'GU'	=>	'Guam',
	'GT'	=>	'Guatemala',
	'GN'	=>	'Guinea',
	'GW'	=>	'Guinea-Bissau',
	'GY'	=>	'Guyana',
	'HT'	=>	'Haiti',
	'HM'	=>	'Heard And Mc Donald Islands',
	'HN'	=>	'Honduras',
	'HK'	=>	'Hong Kong',
	'HU'	=>	'Hungary',
	'IS'	=>	'Iceland',
	'IN'	=>	'India',
	'IR'	=>	'Iran (Islamic Republic Of)',
	'IQ'	=>	'Iraq',
	'IE'	=>	'Ireland',
	'IL'	=>	'Israel',
	'IT'	=>	'Italy',
	'JM'	=>	'Jamaica',
	'JP'	=>	'Japan',
	'JO'	=>	'Jordan',
	'KZ'	=>	'Kazakhstan',
	'KE'	=>	'Kenya',
	'KI'	=>	'Kiribati',
	'KP'	=>	'Korea, Democratic People\'S Republic Of',
	'KR'	=>	'Korea, Republic Of',
	'KW'	=>	'Kuwait',
	'KG'	=>	'Kyrgyzstan',
	'LA'	=>	'Lao People\'S Democratic Republic',
	'LV'	=>	'Latvia',
	'LB'	=>	'Lebanon',
	'LS'	=>	'Lesotho',
	'LR'	=>	'Liberia',
	'LY'	=>	'Libyan Arab Jamahiriya',
	'LI'	=>	'Liechtenstein',
	'LT'	=>	'Lithuania',
	'LU'	=>	'Luxembourg',
	'MO'	=>	'Macau',
	'MK'	=>	'Macedonia, Former Yugoslav Republic Of',
	'MG'	=>	'Madagascar',
	'MW'	=>	'Malawi',
	'MY'	=>	'Malaysia',
	'MV'	=>	'Maldives',
	'ML'	=>	'Mali',
	'MT'	=>	'Malta',
	'MH'	=>	'Marshall Islands, Republic of the',
	'MQ'	=>	'Martinique',
	'MR'	=>	'Mauritania',
	'MU'	=>	'Mauritius',
	'YT'	=>	'Mayotte',
	'MX'	=>	'Mexico',
	'FM'	=>	'Micronesia, Federated States Of',
	'MD'	=>	'Moldova, Republic Of',
	'MC'	=>	'Monaco',
	'MN'	=>	'Mongolia',
	'MS'	=>	'Montserrat',
	'MA'	=>	'Morocco',
	'MZ'	=>	'Mozambique',
	'MM'	=>	'Myanmar',
	'NA'	=>	'Namibia',
	'NR'	=>	'Nauru',
	'NP'	=>	'Nepal',
	'NL'	=>	'Netherlands',
	'AN'	=>	'Netherlands Antilles',
	'NC'	=>	'New Caledonia',
	'NZ'	=>	'New Zealand',
	'NI'	=>	'Nicaragua',
	'NE'	=>	'Niger',
	'NG'	=>	'Nigeria',
	'NU'	=>	'Niue',
	'NF'	=>	'Norfolk Island',
	'ND'	=>	'Northern Ireland',
	'MP'	=>	'Northern Mariana Islands, Commonwealth of the',
	'NO'	=>	'Norway',
	'OM'	=>	'Oman',
	'PK'	=>	'Pakistan',
	'PW'	=>	'Palau, Republic of',
	'PA'	=>	'Panama',
	'PG'	=>	'Papua New Guinea',
	'PY'	=>	'Paraguay',
	'PE'	=>	'Peru',
	'PH'	=>	'Philippines',
	'PN'	=>	'Pitcairn',
	'PL'	=>	'Poland',
	'PT'	=>	'Portugal',
	'PR'	=>	'Puerto Rico',
	'QA'	=>	'Qatar',
	'RE'	=>	'Reunion',
	'RO'	=>	'Romania',
	'RU'	=>	'Russian Federation',
	'RW'	=>	'Rwanda',
	'KN'	=>	'Saint Kitts And Nevis',
	'LC'	=>	'Saint Lucia',
	'VC'	=>	'Saint Vincent And The Grenadines',
	'WS'	=>	'Samoa',
	'SM'	=>	'San Marino',
	'ST'	=>	'Sao Tome And Principe',
	'SS'	=>	'Scotland',
	'SN'	=>	'Senegal',
	'SC'	=>	'Seychelles',
	'SL'	=>	'Sierra Leone',
	'SG'	=>	'Singapore',
	'SK'	=>	'Slovakia (Slovak Republic)',
	'SI'	=>	'Slovenia',
	'SB'	=>	'Solomon Islands',
	'SO'	=>	'Somalia',
	'ZA'	=>	'South Africa',
	'GS'	=>	'South Georgia, South Sandwich Islands',
	'ES'	=>	'Spain',
	'LK'	=>	'Sri Lanka',
	'SH'	=>	'St. Helena',
	'PM'	=>	'St. Pierre And Miquelon',
	'SD'	=>	'Sudan',
	'SR'	=>	'Suriname',
	'SJ'	=>	'Svalbard And Jan Mayen Islands',
	'SZ'	=>	'Swaziland',
	'SE'	=>	'Sweden',
	'CH'	=>	'Switzerland',
	'SY'	=>	'Syrian Arab Republic',
	'TW'	=>	'Taiwan',
	'TJ'	=>	'Tajikistan',
	'TZ'	=>	'Tanzania, United Republic Of',
	'TH'	=>	'Thailand',
	'TG'	=>	'Togo',
	'TK'	=>	'Tokelau',
	'TO'	=>	'Tonga',
	'TT'	=>	'Trinidad And Tobago',
	'TN'	=>	'Tunisia',
	'TR'	=>	'Turkey',
	'TM'	=>	'Turkmenistan',
	'TC'	=>	'Turks And Caicos Islands',
	'TV'	=>	'Tuvalu',
	'UG'	=>	'Uganda',
	'UA'	=>	'Ukraine',
	'AE'	=>	'United Arab Emirates',
	'GB'	=>	'United Kingdom',
	'UM'	=>	'United States Minor Outlying Islands',
	'UY'	=>	'Uruguay',
	'UZ'	=>	'Uzbekistan',
	'VU'	=>	'Vanuatu',
	'VA'	=>	'Vatican City, State of the',
	'VE'	=>	'Venezuela',
	'VN'	=>	'Viet Nam',
	'VG'	=>	'Virgin Islands (British)',
	'VI'	=>	'Virgin Islands (U.S.)',
	'WL'    =>  'Wales',
	'WF'	=>	'Wallis And Futuna Islands',
	'EH'	=>	'Western Sahara',
	'YE'	=>	'Yemen',
	'YU'	=>	'Yugoslavia',
	'ZM'	=>	'Zambia',
	'ZW'	=>	'Zimbabwe'
);
